### ISSUE TITLE
Better card for vrtnws

### ISSUE THREAD

**Issue by elRadix** [thibmaek/custom-components#13]
Just want to share that I have been able to have useful card with the following config using some custom cards below

https://github.com/thomasloven/lovelace-useful-markdown-card
https://github.com/ciotlosm/custom-lovelace/tree/master/entity-attributes-card

```
type: entities
show_header_toggle: false
entities:
  - content: |
      ##### vrtnws.be
      ### [[ sensor.vrt_nws ]]  
       ![vrtnws]([[ sensor.vrt_nws.attributes.picture ]])  
    type: 'custom:useful-markdown-card'
  - type: 'custom:entity-attributes-card'
    filter:
      include:
        - key: sensor.vrt_nws.details*
          name: ' '
    heading_name: ' '
    heading_state: ' '
  - content: |
      [Lees meer] [[ sensor.vrt_nws.attributes.link ]]      
    type: 'custom:useful-markdown-card'

```

which will give you this view, maybe more tweak are required regarding the title:
![image](https://user-images.githubusercontent.com/6258894/56321609-64ab8980-6167-11e9-841a-f2333c4bbe84.png)

**Comment by thibmaek** [comment]
That's nice! I will update the README with this example.

**Comment by elRadix** [comment]
another updates, made it more simpeler using only 1 custom card but had to create a template sensor to caputure news text only

template sensor
```
      vrt_text:
        entity_id: sensor.vrt_nws
        value_template: '{{states.sensor.vrt_nws.attributes.details}}'
        friendly_name: 'vrt text'  
```

card config
```
entities:
  - content: |
     ###### vrtnws.be
     ### [[ sensor.vrt_nws ]]  
     ![vrtnws]([[ sensor.vrt_nws.attributes.picture ]])  
     [[ sensor.vrt_text ]]      
     ###### [Lees meer] [[ sensor.vrt_nws.attributes.link ]]      
    type: 'custom:useful-markdown-card'
type: entities 
```

now it looks much better with 1 full card

![image](https://user-images.githubusercontent.com/6258894/56355843-a1af6480-61d7-11e9-97c2-70fd5e02810f.png)

**Comment by elRadix** [comment]
seems not to be working very well the template sensor

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 326, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 920, in async_set
    context)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 687, in __init__
    "State max length is 255 characters.").format(entity_id))
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.vrt_text. State max length is 255 characters.
```

**Comment by thibmaek** [comment]
You could manually truncate it in the templating string I think

**Comment by elRadix** [comment]
thank you for the tip! added truncate no more errors 

```
      vrt_text:
        entity_id: sensor.vrt_nws,sensor.time
        value_template: '{{states.sensor.vrt_nws.attributes.details | truncate(255) }}'
        friendly_name: 'vrt text'  
```
text truncated below
![image](https://user-images.githubusercontent.com/6258894/56359718-a0376980-61e2-11e9-86c1-a660a85253ff.png)

**Comment by thibmaek** [comment]
I'll see when I can find the time to get this in order but have added it to my roadmap for now: https://www.notion.so/thibmaek/Add-docs-for-custom-card-suggestion-55d106d1fe3d491eb17821e9645ba820
